# Generated by Django 4.1.7 on 2023-07-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0003_checklist_footer_checklist_header_user_rights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('LogData_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_ID', models.IntegerField()),
                ('Next_User_ID', models.IntegerField()),
                ('Date_Time', models.DateTimeField()),
                ('Doc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.checklist_trans_header')),
                ('Next_User_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logdata_nextusername', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logdata_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
