# Generated by Django 4.1.7 on 2023-07-13 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0004_logdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structural_Element',
            fields=[
                ('Struc_Ele_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Structural_Element', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Structural_Element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.structural_element'),
        ),
    ]
