# Generated by Django 4.1.7 on 2023-07-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0006_alter_checklist_trans_header_project_head_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_footer',
            name='CheckList_Item_Desc',
            field=models.TextField(),
        ),
    ]
