# Generated by Django 4.1.7 on 2023-07-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0008_alter_checklist_trans_header_project_head_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_trans_details',
            name='id',
        ),
        migrations.AddField(
            model_name='checklist_trans_details',
            name='CheckList_Trans_Details_ID',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
