# Generated by Django 4.1.7 on 2023-07-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0009_remove_checklist_trans_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='CheckList_Trans_Details_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
