# Generated by Django 4.1.7 on 2023-07-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0010_alter_checklist_trans_details_checklist_trans_details_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_trans_header',
            name='Chainage',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checklist_trans_header',
            name='Name_Of_ABLStaff',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='checklist_trans_header',
            name='Site_Name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='checkapp.site_master'),
        ),
    ]
