# Generated by Django 4.1.7 on 2023-07-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0012_alter_checklist_trans_details_checklist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='CheckList_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.checklist_trans_header'),
        ),
    ]
