# Generated by Django 4.1.7 on 2023-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0013_alter_checklist_trans_details_checklist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Site_DH_EQA_Status',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA'), ('4', 'Partial')], default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Site_Engineer_Status',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA'), ('4', 'Partial')], default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Project_Head_Status',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Quality_Engineer_status',
            field=models.CharField(blank=True, choices=[('1', 'Well implimented Quality Checks'), ('2', 'Fairly implimented Quality Checks'), ('3', 'Poorly implimented Quality Checks')], default=None, max_length=70),
        ),
    ]
