# Generated by Django 4.1.7 on 2023-07-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0014_alter_checklist_trans_details_site_dh_eqa_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Project_Head_Status',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Quality_Engineer_status',
            field=models.CharField(blank=True, choices=[('1', 'Well implimented Quality Checks'), ('2', 'Fairly implimented Quality Checks'), ('3', 'Poorly implimented Quality Checks')], max_length=70),
        ),
    ]
