# Generated by Django 4.1.7 on 2023-07-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0015_alter_checklist_trans_header_project_head_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList_Trans_Header_Draft',
            fields=[
                ('Doc_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name_Of_ABLStaff', models.CharField(default=True, max_length=100)),
                ('inspection_Start_Date', models.DateTimeField(blank=True, null=True)),
                ('inspection_End_Date', models.DateTimeField(blank=True, null=True)),
                ('Contractor', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Chainage', models.CharField(default=True, max_length=100)),
                ('Quality_Engineer_status', models.CharField(blank=True, choices=[('1', 'Well implimented Quality Checks'), ('2', 'Fairly implimented Quality Checks'), ('3', 'Poorly implimented Quality Checks')], max_length=70)),
                ('Project_Head_Status', models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], max_length=70)),
                ('CheckList_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.checklist_header')),
                ('Project_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.project_master')),
                ('Site_Name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='checkapp.site_master')),
                ('Structural_Element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.structural_element')),
            ],
        ),
        migrations.CreateModel(
            name='CheckList_Trans_Details_Draft',
            fields=[
                ('CheckList_Trans_Details_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Doc_ID', models.IntegerField()),
                ('Site_Engineer_Status', models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA'), ('4', 'Partial')], default=None, max_length=70)),
                ('Site_DH_EQA_Status', models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA'), ('4', 'Partial')], default=None, max_length=70)),
                ('Site_Engineer_Comment', models.TextField(blank=True)),
                ('Site_DH_EQA_Comment', models.TextField(blank=True)),
                ('CheckList_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.checklist_trans_header')),
                ('CheckList_Item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkapp.checklist_footer')),
            ],
        ),
    ]
