# Generated by Django 4.1.7 on 2023-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0017_alter_checklist_trans_details_draft_site_dh_eqa_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details_draft',
            name='Site_DH_EQA_Status',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA'), ('4', 'Partial')], max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details_draft',
            name='Site_Engineer_Status',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA'), ('4', 'Partial')], max_length=70),
        ),
    ]
