# Generated by Django 4.1.7 on 2023-07-25 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0019_alter_checklist_trans_details_site_dh_eqa_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='CheckList_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_id_details', to='checkapp.checklist_trans_header'),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Doc_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_id_details', to='checkapp.checklist_trans_header'),
        ),
    ]
