# Generated by Django 4.1.7 on 2023-07-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0020_alter_checklist_trans_details_checklist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='CheckList_Item_ID',
            field=models.CharField(max_length=200),
        ),
    ]
