# Generated by Django 4.1.7 on 2023-07-27 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0021_alter_checklist_trans_details_checklist_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details_draft',
            name='CheckList_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_id_details_draft', to='checkapp.checklist_trans_header'),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details_draft',
            name='CheckList_Item_ID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details_draft',
            name='Doc_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_id_details_draft', to='checkapp.checklist_trans_header'),
        ),
    ]
