# Generated by Django 4.1.7 on 2023-07-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0022_alter_checklist_trans_details_draft_checklist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details_draft',
            name='CheckList_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_id_details_draft', to='checkapp.checklist_trans_header_draft'),
        ),
    ]
