# Generated by Django 4.1.7 on 2023-07-27 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0025_checklist_trans_header_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_trans_header_draft',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header_draft',
            name='Name_Of_ABLStaff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_draft', to=settings.AUTH_USER_MODEL),
        ),
    ]
