# Generated by Django 4.1.7 on 2023-07-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0026_checklist_trans_header_draft_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_trans_header',
            name='checklist_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Pending', 'Pending')], default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist_trans_header',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_trans_header_draft',
            name='checklist_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='None', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist_trans_header_draft',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
