# Generated by Django 4.1.7 on 2023-07-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0027_checklist_trans_header_checklist_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Site_DH_EQA_Comment',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Site_Engineer_Comment',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
