# Generated by Django 4.1.7 on 2023-07-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0028_alter_checklist_trans_details_site_dh_eqa_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Site_DH_EQA_Status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA'), ('Partial', 'Partial')], max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Site_Engineer_Status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Na', 'NA'), ('Partial', 'Partial')], max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details_draft',
            name='Site_DH_EQA_Status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA'), ('Partial', 'Partial')], max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details_draft',
            name='Site_Engineer_Status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Na', 'NA'), ('Partial', 'Partial')], max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Project_Head_Status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Quality_Engineer_status',
            field=models.CharField(blank=True, choices=[('Well implimented Quality Checks', 'Well implimented Quality Checks'), ('Fairly implimented Quality Checks', 'Fairly implimented Quality Checks'), ('Poorly implimented Quality Checks', 'Poorly implimented Quality Checks')], max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header_draft',
            name='Project_Head_Status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header_draft',
            name='Quality_Engineer_status',
            field=models.CharField(blank=True, choices=[('Well implimented Quality Checks', 'Well implimented Quality Checks'), ('Fairly implimented Quality Checks', 'Fairly implimented Quality Checks'), ('Poorly implimented Quality Checks', 'Poorly implimented Quality Checks')], max_length=70),
        ),
    ]
