# Generated by Django 4.1.7 on 2023-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0031_alter_checklist_trans_details_draft_site_engineer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Site_Engineer_Status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Na', 'NA'), ('Partial', 'Partial')], default='Unspecified', max_length=70),
        ),
    ]
