# Generated by Django 4.1.7 on 2023-08-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0032_alter_checklist_trans_details_site_engineer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Site_DH_EQA_Status',
            field=models.CharField(choices=[('Yes', ' Yes'), ('No', ' No'), ('NA', ' NA'), ('Partial', ' Partial')], default='Unspecified', max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details',
            name='Site_Engineer_Status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Na', 'NA'), ('Partial', 'Partial')], default='Unspecified', max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_details_draft',
            name='Site_DH_EQA_Status',
            field=models.CharField(choices=[('Yes', ' Yes'), ('No', ' No'), ('NA', ' NA'), ('Partial', ' Partial')], max_length=70),
        ),
    ]
