# Generated by Django 4.1.7 on 2023-08-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0033_alter_checklist_trans_details_site_dh_eqa_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_trans_header_draft',
            name='CheckList_ID',
        ),
        migrations.RemoveField(
            model_name='checklist_trans_header_draft',
            name='Name_Of_ABLStaff',
        ),
        migrations.RemoveField(
            model_name='checklist_trans_header_draft',
            name='Project_Name',
        ),
        migrations.RemoveField(
            model_name='checklist_trans_header_draft',
            name='Site_Name',
        ),
        migrations.RemoveField(
            model_name='checklist_trans_header_draft',
            name='Structural_Element',
        ),
        migrations.RemoveField(
            model_name='checklist_trans_header_draft',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_Administrator',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
        migrations.DeleteModel(
            name='CheckList_Trans_Details_Draft',
        ),
        migrations.DeleteModel(
            name='CheckList_Trans_Header_Draft',
        ),
    ]
