# Generated by Django 4.1.7 on 2023-08-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0034_remove_checklist_trans_header_draft_checklist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_DHEQA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_ProjectHead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_ProjectQA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_SiteEngineer',
            field=models.BooleanField(default=False),
        ),
    ]
