# Generated by Django 4.1.7 on 2023-09-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0035_customuser_is_dheqa_customuser_is_projecthead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_footer',
            name='Initial_Checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_footer',
            name='Inprocess_Checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_footer',
            name='Post_Checks',
            field=models.BooleanField(default=False),
        ),
    ]
