# Generated by Django 4.1.7 on 2023-09-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0037_checklist_trans_header_assigned_to_is_dheqa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_trans_header',
            name='assigned_to_is_DHEQA',
        ),
        migrations.RemoveField(
            model_name='checklist_trans_header',
            name='assigned_to_is_ProjectHead',
        ),
        migrations.RemoveField(
            model_name='checklist_trans_header',
            name='assigned_to_is_ProjectQA',
        ),
    ]
