# Generated by Django 4.1.7 on 2023-09-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0038_remove_checklist_trans_header_assigned_to_is_dheqa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Project_Head_Status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Unspecified', max_length=70),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Quality_Engineer_status',
            field=models.CharField(blank=True, choices=[('Well implimented Quality Checks', 'Well implimented Quality Checks'), ('Fairly implimented Quality Checks', 'Fairly implimented Quality Checks'), ('Poorly implimented Quality Checks', 'Poorly implimented Quality Checks')], default='Unspecified', max_length=70),
        ),
    ]
