# Generated by Django 4.1.7 on 2023-09-08 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0040_alter_checklist_trans_header_inspection_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_trans_header',
            name='assigned_to_ProjectHead',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to_ProjectHead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist_trans_header',
            name='assigned_to_ProjectQA',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to_ProjectQA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
