# Generated by Django 4.1.7 on 2023-09-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0042_rename_assigned_to_projecthead_checklist_trans_header_submit_to_projecthead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist_trans_header',
            name='submit_to_ProjectHead',
        ),
        migrations.RemoveField(
            model_name='checklist_trans_header',
            name='submit_to_ProjectQA',
        ),
    ]
