# Generated by Django 4.1.7 on 2023-09-09 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0043_remove_checklist_trans_header_submit_to_projecthead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_trans_header',
            name='assigned_to_DHEQA',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to_DHEQA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist_trans_header',
            name='assigned_to_ProjectHead',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to_ProjectHead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist_trans_header',
            name='assigned_to_ProjectQA',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to_ProjectQA', to=settings.AUTH_USER_MODEL),
        ),
    ]
