# Generated by Django 4.1.7 on 2023-09-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0047_checklist_trans_header_rejected_bydheqa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='checklist_status',
            field=models.CharField(choices=[('Completed_By_SiteEngineer & Pending_By_DHEQA', 'Completed_By_SiteEngineer & Pending_By_DHEQA'), ('Completed_By_SiteEngineer & Active_At_DHEQA', 'Completed_By_SiteEngineer & Active_At_DHEQA'), ('Completed_By_DHEQA & Pending_By_ProjectQA', 'Completed_By_DHEQA & Pending_By_ProjectQA'), ('Completed_By_DHEQA & Active_At_ProjectQA', 'Completed_By_DHEQA & Active_At_ProjectQA'), ('Completed_By_ProjectQA & Pending_By_ProjectHead', 'Completed_By_ProjectQA & Pending_By_ProjectHead'), ('Completed_By_ProjectQA & Active_At_ProjectHead', 'Completed_By_ProjectQA & Active_At_ProjectHead'), ('Completed_By_ProjectHead', 'Completed_By_ProjectHead'), ('Rejected', 'Rejected')], max_length=70),
        ),
    ]
