# Generated by Django 4.1.7 on 2023-10-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0048_alter_checklist_trans_header_checklist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist_trans_header',
            name='Quality_Engineer_Comment',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='checklist_trans_header',
            name='Chainage',
            field=models.CharField(max_length=100),
        ),
    ]
