# Generated by Django 4.1.7 on 2023-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0049_checklist_trans_header_quality_engineer_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('History_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Doc_ID', models.CharField(max_length=100)),
                ('Date_Time', models.DateTimeField()),
                ('Comment', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
